dist:     trusty
sudo:     required

language: cpp

os:
  - linux

before_install:
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -y valgrind libboost-dev libboost-system-dev 

compiler:
  - g++
  - clang++ 

env:
  - BUILD_TYPE=Debug STANDARD=11
  - BUILD_TYPE=Release STANDARD=11
  - BUILD_TYPE=Debug STANDARD=14
  - BUILD_TYPE=Release STANDARD=14
  - BUILD_TYPE=Debug STANDARD=17
  - BUILD_TYPE=Release STANDARD=17

matrix:
  exclude:
  - compiler: g++
    env: BUILD_TYPE=Debug STANDARD=14
  - compiler: g++
    env: BUILD_TYPE=Release STANDARD=14
  - compiler: g++
    env: BUILD_TYPE=Debug STANDARD=17
  - compiler: g++
    env: BUILD_TYPE=Release STANDARD=17
  
script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTING=ON -DPARANOID_WARNING=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=$STANDARD
    - cmake --build .
    - ctest --output-on-failure
